version: "2.4"
services:
  app:
    build:
      target: dev
      context: .
    ports:
      - "3000:3000"
      - "4040:4040"
    environment:
      NGROK_MAPPING: |
        {
          "/cats": "example-image-cats",
          "/dogs": "example-image-dogs"
        }
      NGROK_INSPECT: "true"
      IMGIX_DOMAIN: testing.imgix.net
      IMGIX_TOKEN: <SECURE_URL_TOKEN>
  example-image:
    image: nginx:1.19.2
    volumes:
      - ./example:/usr/share/nginx/html:ro
